[+] parntersList <- Remove apiViz and adding Data4Good/Latitude
CodeforFR/enthic-dataviz pull request #20
Opened 2021-04-11 16:09 UTC by QuentinMadura

This PR is related to the issue https://github.com/CodeforFR/enthic-dataviz/issues/8 .
It introduces :

2021-04-11 18:18 UTC, JulienRobberechts requested changes
En fait au début je suis parti sur du css natif pour cette page et ensuite j'ai fait des copier-coller du bulma, donc c'est un peu le bordel coté css désolé.

Les pb que je vois:
- le logo dataforgood est un peu gros par rapport au autres
- j'ai oublié de recopier tous les styles donc par exemple mg-mini n'est pas défini
- en screen mobile les icones sont trop gros.

Bref, j'ai pas fini le boulot, tu peux corriger tout ca ou laisser ca pour plus tard :-)

2021-04-12 06:43 UTC, QuentinMadura commented
@JulienRobberechts, je m'occupe de corriger ça :)

2021-04-12 13:25 UTC, QuentinMadura commented
Done :)

2021-04-12 17:29 UTC, JulienRobberechts commented
J'ai supprimé qq styles inutiles et mis la partenaires sur une seule ligne.

2021-04-12 17:29 UTC, JulienRobberechts approved these changes

2021-04-12 17:32 UTC, JulienRobberechts approved these changes
OK

2021-04-12 17:33 UTC, merged