[+] SearchBar <- adding text in the search bar
CodeforFR/enthic-dataviz pull request #33
Opened 2021-04-20 08:31 UTC by QuentinMadura

This PR includes :
Changing search text in the search bar on the search page.

Issue related : https://github.com/CodeforFR/enthic-dataviz/issues/31

2021-04-20 08:40 UTC, leonarf requested changes
D'un point de vu fonctionnel, ce n'est pas ce à quoi je m'attendais : le texte de la recherche apparais bien dans la barre de recherche, mais en tant que "place holder" c'est à dire que l'utilisateur peut écrire par dessus, et non pas éditer ça recherche.

2021-04-21 17:11 UTC, JulienRobberechts commented
> D'un point de vu fonctionnel, ce n'est pas ce à quoi je m'attendais : le texte de la recherche apparais bien dans la barre de recherche, mais en tant que "place holder" c'est à dire que l'utilisateur peut écrire par dessus, et non pas éditer ça recherche.

Oui je suis d’accord. Je pense que placeholder n'est pas ce que tu voulais faire @QuentinMadura. Tu voulais probablement faire un binding de la valeur du texte (avec un attribut v-model)

2021-05-19 08:38 UTC, JulienRobberechts commented
J'ai modifié la barre de recherche. @leonarf est ce que ça te va ?

2021-05-19 09:59 UTC, leonarf approved these changes
Je valide le fonctionnel :-)

2021-05-19 09:59 UTC, merged