14/improve website interface
CodeforFR/enthic-dataviz pull request #34
Opened 2021-04-20 12:45 UTC by QuentinMadura

This PR introduces :
[+] UI Improvements
[-+] Cleaning CSS 
[+] Style homogenisation

2021-04-21 07:14 UTC, leonarf requested changes
Je trouve l'ergonomie du site beaucoup mieux avec cette PR, et ça me fait remarquer qu'il y a encore du "apiviz" qui traine dans des fichiers ou nom de fichier : je vais faire une issue la dessus. Il y a des répétitions dans les textes de la homepage mais on pourra le retravailler plus tard. J'ai juste une demande de modification : sur la page de détail (par ex https://deploy-preview-34--enthic-dataviz.netlify.app/entreprises/443061841), les titres "Autres données présentes dans la base Enthic, mais pas valorisées ici :" et "Autre représentation des comptes de résultat " ne prennent pas toute la largeur dont ils disposent, et chez moi, le mot 'représentation' est même coupé en deux par un retour à la ligne alors qu'il y a plein de place à droite. Ça c'était ma relecture fonctionnelle. Pour la relecture du code, je laisse la main :-)

2021-04-21 17:18 UTC, JulienRobberechts requested changes
Très sympa cette nouvelle home page !

2021-04-21 17:18 UTC, JulienRobberechts commented on src/components/company/DynamicDetail.vue
> +              <h3 class="tile title is-3">
is-3 pose problème en effet ici

2021-04-21 17:18 UTC, JulienRobberechts commented on src/components/company/DynamicDetail.vue
> +              <h3 class="tile title is-3">
idem, is-3 pose problème en effet ici

2021-04-21 17:20 UTC, JulienRobberechts commented
le logo Wexample ne s'affiche pas.

2021-04-22 07:00 UTC, leonarf commented
> le logo Wexample ne s'affiche pas.

C'est leur site qui a changé, je vais faire une issue, ou m'en occuper moi-même

2021-05-19 08:13 UTC, JulienRobberechts commented
J'ai juste corrigé les titres de la dernière section et supprimer les liens web et contact (see_website , see_contact).
@leonarf Est-ce que sur cette PR il y a d'autres choses à faire pour merger ?

2021-05-19 10:01 UTC, leonarf approved these changes
Ça me parait très bien, je valide et merge

2021-05-19 10:02 UTC, merged